sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Qaz572455256

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJNTft8JSHW6tSfhNfS
    access-key-secret: L7dvn9j7hfV0eP6VQzUVeqUsYRTAsV
    bucket-name: sky-melzj

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx6a50b98fe9b67007
    secret: 75ebd3e5ebe93bc4d97e68a2ee0aeda9